- name: Deploy TravelMemory MERN App
  hosts: web
  become: yes
  vars:
    repo_url: "https://github.com/UnpredictablePrashant/TravelMemory.git"

    mongo_url: "mongodb://mongo:mongo@{{ hostvars['db']['ansible_host'] }}:27017/travelmemory?authSource=travelmemory"
  tasks:

    - name: Clone application
      git:
        repo: "{{ repo_url }}"
        dest: /opt/travelmemory
        version: main
        force: yes

    - name: Install backend dependencies
      shell: npm install
      args:
        chdir: /opt/travelmemory/backend

    - name: Create .env for backend
      copy:
        dest: /opt/travelmemory/backend/.env
        content: |
          MONGO_URL={{ mongo_url }}
          PORT=5000

    - name: Start backend using PM2
      shell: pm2 start index.js --name travel-api
      args:
        chdir: /opt/travelmemory/backend

    - name: Install frontend dependencies
      shell: npm install
      args:
        chdir: /opt/travelmemory/frontend

    - name: Create .env for frontend (React)
      copy:
        dest: /opt/travelmemory/frontend/.env
        content: |
          REACT_APP_BACKEND_URL=http://{{ hostvars['web'].ansible_host }}:5000

    - name: Build frontend
      shell: npm run build
      args:
        chdir: /opt/travelmemory/frontend

    - name: Serve frontend with PM2
      shell: pm2 serve build 3000 --name travel-ui --spa
      args:
        chdir: /opt/travelmemory/frontend
