---
- name: Install Docker & MongoDB container (Ubuntu 24.04)
  hosts: db
  become: yes

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
      args:
        creates: /usr/share/keyrings/docker.gpg

    - name: Add Docker Bookworm Repository (works on Ubuntu 24.04)
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable

    - name: Install Docker engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Start Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull MongoDB Docker image
      community.docker.docker_image:
        name: mongo
        tag: "7.0"
        source: pull

    - name: Run MongoDB container with user/password and DB
      community.docker.docker_container:
        name: mongodb
        image: "mongo:7.0"
        state: started
        restart_policy: always
        ports:
          - "27017:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: mongo
          MONGO_INITDB_DATABASE: travelmemory
